# @package _group_

ds_train_acordar1_fold_0_metadata_content_illusnip:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /1stage/traindata_metadata_illusnip_fold_0.json

ds_dev_acordar1_fold_0_metadata_content_illusnip:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /acordar1_qrel/ds_metadata_content_illusnip_split_3.json

ds_train_acordar1_fold_1_metadata_content_illusnip:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /1stage/traindata_metadata_illusnip_fold_1.json

ds_dev_acordar1_fold_1_metadata_content_illusnip:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /acordar1_qrel/ds_metadata_content_illusnip_split_4.json

ds_train_acordar1_fold_2_metadata_content_illusnip:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /1stage/traindata_metadata_illusnip_fold_2.json

ds_dev_acordar1_fold_2_metadata_content_illusnip:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /acordar1_qrel/ds_metadata_content_illusnip_split_0.json

ds_train_acordar1_fold_3_metadata_content_illusnip:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /1stage/traindata_metadata_illusnip_fold_3.json

ds_dev_acordar1_fold_3_metadata_content_illusnip:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /acordar1_qrel/ds_metadata_content_illusnip_split_1.json

ds_train_acordar1_fold_4_metadata_content_illusnip:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /1stage/traindata_metadata_illusnip_fold_4.json

ds_dev_acordar1_fold_4_metadata_content_illusnip:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /acordar1_qrel/ds_metadata_content_illusnip_split_2.json